"use client";
import {useMemo,useState} from "react";
import {motion,AnimatePresence} from "framer-motion";
import {Car,BrainCircuit,Settings2,Trophy,Home,Search,X,Zap,Cog,ShieldCheck,CheckCircle2} from "lucide-react";
import data from "../data/vehicle.json";

type Item=(typeof data.categories)[number]["components"][number];
type Diag=(typeof data.diagnostics)[number];
const levels:any={green:["אפשר להמשיך בזהירות","border-emerald-400/30 bg-emerald-500/10 text-emerald-300"],yellow:["בדיקה בהקדם","border-amber-400/30 bg-amber-500/10 text-amber-300"],red:["עצור ובדוק מיד","border-red-400/30 bg-red-500/10 text-red-300"]};

export default function Page(){
 const [section,setSection]=useState("home"),[cat,setCat]=useState<"electrical"|"mechanical">("electrical"),[q,setQ]=useState(""),[selected,setSelected]=useState<Item|null>(null),[diag,setDiag]=useState<Diag|null>(null),[qi,setQi]=useState(0),[xp,setXp]=useState(0),[answer,setAnswer]=useState<number|null>(null);
 const items=useMemo(()=>data.categories.find(x=>x.id===cat)!.components.filter(x=>(x.name+x.group+x.how).includes(q)),[cat,q]);
 const go=(s:string)=>{setSection(s);window.scrollTo({top:0,behavior:"smooth"})};
 return <main dir="rtl" className="min-h-screen bg-slateDeep text-slate-50 grid-bg pb-24 lg:pb-0">
  <aside className="fixed right-0 top-0 hidden h-screen w-72 border-l border-slate-700/50 bg-[#0b1220]/95 p-5 backdrop-blur-xl lg:block">
   <div className="mb-8 flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-cyan-500/15 text-cyan-300"><Car/></div><div><b className="text-xl">CarPedia <span className="text-cyan-300">360</span></b><p className="text-xs text-slate-400">הכרת הרכב והחשמל</p></div></div>
   <nav aria-label="ניווט ראשי" className="space-y-2">{[["home","בית",Home],["explorer","סייר הרכב",Car],["diagnostic","רופא הרכב",BrainCircuit],["maintenance","תחזוקה",Settings2],["quiz","חידונים",Trophy]].map(([id,label,I]:any)=><button key={id} onClick={()=>go(id)} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-right ${section===id?"bg-cyan-400/10 text-cyan-200":"text-slate-300 hover:bg-white/5"}`}><I size={19}/>{label}</button>)}</nav>
   <div className="absolute bottom-6 left-5 right-5 rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-4"><div className="flex items-center gap-2 text-emerald-300"><ShieldCheck size={18}/><b>נגישות פעילה</b></div><p className="mt-2 text-xs leading-5 text-slate-400">RTL, ניווט מקלדת, פוקוס ברור ותמיכה בקורא מסך.</p></div>
  </aside>
  <header className="sticky top-0 z-20 border-b border-slate-700/40 bg-[#0b1220]/90 px-4 py-3 backdrop-blur-xl lg:mr-72"><div className="mx-auto flex max-w-6xl justify-between"><span className="text-sm text-slate-400">● מערכת פעילה</span><b className="lg:hidden">CarPedia 360</b></div></header>
  <div className="lg:mr-72"><div className="mx-auto max-w-6xl px-4 py-7 sm:px-6">
   <AnimatePresence mode="wait">
    {section==="home"&&<Home go={go} xp={xp}/>}
    {section==="explorer"&&<Explorer items={items} cat={cat} setCat={setCat} q={q} setQ={setQ} select={setSelected}/>}
    {section==="diagnostic"&&<Diagnostic diag={diag} setDiag={setDiag}/>}
    {section==="maintenance"&&<Maintenance/>}
    {section==="quiz"&&<Quiz i={qi} setI={setQi} xp={xp} setXp={setXp} answer={answer} setAnswer={setAnswer}/>}
   </AnimatePresence>
  </div></div>
  <nav aria-label="ניווט נייד" className="fixed bottom-0 left-0 right-0 z-30 grid grid-cols-5 border-t border-slate-700/50 bg-[#0b1220]/95 p-2 backdrop-blur-xl lg:hidden">{[["home","בית",Home],["explorer","סייר",Car],["diagnostic","אבחון",BrainCircuit],["maintenance","תחזוקה",Settings2],["quiz","חידון",Trophy]].map(([id,label,I]:any)=><button key={id} onClick={()=>go(id)} className={`py-2 text-xs ${section===id?"text-cyan-300":"text-slate-400"}`}><I size={19} className="mx-auto"/>{label}</button>)}</nav>
  <AnimatePresence>{selected&&<Dialog item={selected} close={()=>setSelected(null)}/>}</AnimatePresence>
 </main>
}

function Home({go,xp}:{go:(s:string)=>void;xp:number}){return <motion.section initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="space-y-6">
 <div className="overflow-hidden rounded-3xl border border-cyan-400/15 bg-gradient-to-br from-cyan-500/10 via-slate-800 to-orange-500/5 p-7 sm:p-10"><span className="rounded-full bg-cyan-500/10 px-3 py-1 text-xs text-cyan-200">ידע שעובד בשבילך</span><h1 className="mt-5 text-4xl font-black sm:text-6xl">הכירו את הרכב.<br/><span className="text-cyan-300">הבינו מה קורה.</span></h1><p className="mt-4 max-w-2xl leading-7 text-slate-300">מדריך אינטראקטיבי בעברית למערכות הרכב, חשמל, תחזוקה ואבחון — פשוט, ברור ונגיש.</p><div className="mt-7 flex gap-3"><button onClick={()=>go("explorer")} className="rounded-xl bg-cyan-500 px-5 py-3 font-bold text-slate-950">לסייר ברכב</button><button onClick={()=>go("diagnostic")} className="rounded-xl border border-slate-600 px-5 py-3 font-bold">רופא הרכב</button></div></div>
 <div className="grid gap-4 sm:grid-cols-3"><Stat title="40+ רכיבים" text="מנוע, בלמים, חשמל, EV ועוד."/><Stat title="אבחון חכם" text="תופעה → סיבה → דחיפות."/><Stat title={xp+" XP"} text="לומדים וצוברים ידע."/></div>
 <div className="grid gap-4 md:grid-cols-2"><Card onClick={()=>go("explorer")} title="חשמל ואלקטרוניקה" text="מצבר, ECU, חיישנים, הצתה, HV ועוד." icon={Zap}/><Card onClick={()=>go("explorer")} title="מכניקה ונוזלים" text="מנוע, קירור, בלמים, מתלים, תמסורת ופליטה." icon={Cog}/></div>
 </motion.section>}
function Stat({title,text}:{title:string;text:string}){return <div className="glass rounded-2xl p-5"><b className="text-lg">{title}</b><p className="mt-2 text-sm text-slate-400">{text}</p></div>}
function Card({title,text,onClick,icon:I}:{title:string;text:string;onClick:()=>void;icon:any}){return <button onClick={onClick} className="glass rounded-2xl p-6 text-right transition hover:-translate-y-1 hover:border-cyan-400/30"><I className="text-cyan-300"/><b className="mt-5 block text-xl">{title}</b><p className="mt-2 text-sm text-slate-400">{text}</p></button>}

function Explorer({items,cat,setCat,q,setQ,select}:{items:Item[];cat:string;setCat:(x:any)=>void;q:string;setQ:(x:string)=>void;select:(x:Item)=>void}){return <motion.section initial={{opacity:0}} animate={{opacity:1}}><Title icon={Car} title="סייר חלקי הרכב והחשמל" text="בחרו רכיב וקבלו הסבר, תסמינים, תחזוקה וטווח עלויות משוער."/>
 <div className="mt-6 flex gap-2"><button onClick={()=>setCat("mechanical")} className={`rounded-xl px-4 py-2 font-bold ${cat==="mechanical"?"bg-orange-500":"bg-slate-800"}`}>מכניקה ונוזלים</button><button onClick={()=>setCat("electrical")} className={`rounded-xl px-4 py-2 font-bold ${cat==="electrical"?"bg-cyan-500 text-slate-950":"bg-slate-800"}`}>חשמל ואלקטרוניקה</button></div>
 <label className="relative mt-4 block"><Search className="absolute right-4 top-3.5 text-slate-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="חיפוש רכיב..." aria-label="חיפוש רכיב" className="w-full rounded-xl border border-slate-700 bg-slate-900 p-3 pr-11"/></label>
 <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.map(x=><button key={x.id} onClick={()=>select(x)} className="glass rounded-2xl p-5 text-right hover:border-cyan-400/30"><span className="text-xs text-slate-500">{x.group}</span><h3 className="mt-2 font-bold">{x.name}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{x.how}</p><span className="mt-4 block text-xs font-bold text-cyan-300">לפרטים ←</span></button>)}</div>
 </motion.section>}
function Title({icon:I,title,text}:{icon:any;title:string;text:string}){return <div className="flex gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-cyan-500/10 text-cyan-300"><I/></span><div><h2 className="text-3xl font-black">{title}</h2><p className="mt-2 leading-7 text-slate-400">{text}</p></div></div>}
function Dialog({item,close}:{item:Item;close:()=>void}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4" role="presentation"><motion.div initial={{scale:.96}} animate={{scale:1}} className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl border border-slate-600 bg-[#101a2c] p-6" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><button onClick={close} aria-label="סגור" className="float-left rounded-lg p-2 hover:bg-white/5"><X/></button><span className="text-xs text-cyan-300">{item.group}</span><h2 id="dialog-title" className="mt-1 text-3xl font-black">{item.name}</h2><Block t="איך זה עובד?">{item.how}</Block><Block t="תסמינים אפשריים"><ul className="list-disc space-y-2 pr-5">{item.symptoms.map(s=><li key={s}>{s}</li>)}</ul></Block><Block t="תחזוקה / החלפה">{item.maintenance}</Block><div className="mt-4 rounded-2xl border border-orange-500/20 bg-orange-500/5 p-4"><b className="text-orange-300">טווח עלויות משוער</b><p className="mt-1 text-sm">{item.cost}</p></div></motion.div></motion.div>}
function Block({t,children}:{t:string;children:any}){return <section className="mt-5 rounded-2xl bg-slate-900/60 p-4"><b className="text-cyan-200">{t}</b><div className="mt-2 text-sm leading-7 text-slate-300">{children}</div></section>}

function Diagnostic({diag,setDiag}:{diag:Diag|null;setDiag:(x:Diag|null)=>void}){return <motion.section initial={{opacity:0}} animate={{opacity:1}}><Title icon={BrainCircuit} title="רופא הרכב" text="בחרו תופעה וקבלו כיוון אבחוני ראשוני ורמת דחיפות. זהו כלי מידע ולא תחליף לבדיקה מקצועית."/><div className="mt-6 grid gap-3 md:grid-cols-2">{data.diagnostics.map(d=><button key={d.id} onClick={()=>setDiag(d)} className="glass rounded-2xl p-5 text-right"><div className="flex justify-between gap-3"><b>{d.title}</b><span className={`rounded-full border px-2 py-1 text-[11px] ${levels[d.level][1]}`}>{levels[d.level][0]}</span></div><p className="mt-2 text-sm text-slate-400">{d.signals.join(" • ")}</p></button>)}</div>{diag&&<div className="mt-6 rounded-3xl border border-slate-600 bg-slate-900 p-6" role="region" aria-live="polite"><button onClick={()=>setDiag(null)} aria-label="סגור" className="float-left"><X/></button><span className={`rounded-full border px-3 py-1 text-xs ${levels[diag.level][1]}`}>{levels[diag.level][0]}</span><h3 className="mt-4 text-2xl font-black">{diag.title}</h3><div className="mt-5 grid gap-4 md:grid-cols-2"><div><b>סיבות אפשריות</b><ul className="mt-2 list-disc space-y-2 pr-5 text-sm text-slate-300">{diag.causes.map(c=><li key={c}>{c}</li>)}</ul></div><div className="rounded-2xl bg-slate-800 p-4"><b>מה עושים?</b><p className="mt-2 text-sm leading-7 text-slate-300">{diag.action}</p></div></div></div>}</motion.section>}
function Maintenance(){return <motion.section initial={{opacity:0}} animate={{opacity:1}}><Title icon={Settings2} title="תחזוקה ובדיקות" text="צ'ק-ליסט כללי לפי קילומטראז'. תמיד יש עדיפות לספר הרכב ולהוראות היצרן."/><div className="mt-6 space-y-3">{data.maintenance.map(m=><div key={m.km} className="glass rounded-2xl p-5"><h3 className="font-black text-cyan-300">{m.km} ק״מ</h3><ul className="mt-3 grid gap-2 sm:grid-cols-3">{m.items.map(x=><li key={x} className="rounded-xl bg-slate-900 p-3 text-sm">✓ {x}</li>)}</ul></div>)}</div></motion.section>}
function Quiz({i,setI,xp,setXp,answer,setAnswer}:{i:number;setI:(x:number)=>void;xp:number;setXp:(x:number)=>void;answer:number|null;setAnswer:(x:number|null)=>void}){const q=data.quiz[i],choose=(n:number)=>{if(answer!==null)return;setAnswer(n);if(n===q.correct)setXp(xp+100)};return <motion.section initial={{opacity:0}} animate={{opacity:1}}><Title icon={Trophy} title="מרכז הידע" text="תרגול קצר. תשובה נכונה מעניקה 100 XP."/><div className="mt-6 rounded-3xl border border-slate-700 bg-slate-900 p-6 sm:p-8"><div className="flex justify-between text-xs text-slate-400"><span>{q.level}</span><span>{i+1}/{data.quiz.length} · {xp} XP</span></div><div className="mt-4 h-2 rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan-400" style={{width:`${(i+1)/data.quiz.length*100}%`}}/></div><h3 className="mt-8 text-2xl font-black leading-10">{q.q}</h3><div className="mt-6 space-y-3">{q.a.map((a,n)=>{const good=answer!==null&&n===q.correct,bad=answer===n&&n!==q.correct;return <button key={a} onClick={()=>choose(n)} className={`w-full rounded-xl border p-4 text-right ${good?"border-emerald-400 bg-emerald-500/10":bad?"border-red-400 bg-red-500/10":"border-slate-700 bg-slate-800/50 hover:border-cyan-400/40"}`}>{a}{good&&<CheckCircle2 className="float-left text-emerald-300"/>}</button>})}</div>{answer!==null&&<button onClick={()=>{setAnswer(null);setI((i+1)%data.quiz.length)}} className="mt-5 rounded-xl bg-cyan-500 px-5 py-3 font-bold text-slate-950">השאלה הבאה</button>}</div></motion.section>}
